server:
  port: 8081

spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/userdb?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    url: jdbc:mysql://49.50.160.38:3306/userdb?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: oidc2020
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    properties.hibernate.hbm2ddl.auto: update # 개발 환경 create-drop
    showSql: true

  messages:
    basename: i18n/exception
    encoding: UTF-8

  jwt:
    secret: oidc2020@&*

  social:
    kakao:
      client_id: ab8785b7a2bf1392b79f98e0266ae60e # 앱생성시 받은 REST API 키
      redirect: /social/login/kakao
      url:
        login: https://kauth.kakao.com/oauth/authorize
        token: https://kauth.kakao.com/oauth/token
        profile: https://kapi.kakao.com/v2/user/me

    naver:
      client_id: X2DQ24UDnPX7o32rmhCI
      client_secret: ZpAUTLaYo8
      redirect: /social/login/naver
      url:
        login: https://nid.naver.com/oauth2.0/authorize
        token: https://nid.naver.com/oauth2.0/token
        profile: https://openapi.naver.com/v1/nid/me
  url:
    base: http://27.96.135.244:8081
#    base:  http://localhost:8081

  application:
    name: service-member

  cloud:
    client:
      hostname: localhost

eureka:
  instance:
    instance-id: inst001
  client:
    service-url:
      defaultZone: http://49.50.173.72:8761/eureka/ # http://localhost:8761/eureka/
