server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/userdb?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: your password here
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    properties.hibernate.hbm2ddl.auto: create
    showSql: true

  messages:
    basename: i18n/exception
    encoding: UTF-8

  jwt:
    secret: jwt secret key

  social:
    kakao:
      client_id: your key here # 앱생성시 받은 REST API 키
      redirect: your redirect uri here
      url:
        login: https://kauth.kakao.com/oauth/authorize
        token: https://kauth.kakao.com/oauth/token
        profile: https://kapi.kakao.com/v2/user/me
  url:
    base: your url here
